version: '3.9'

services:
  WebProxy:
    image: nginx
    ports:
      - "80:80"
    networks:
      - monreseau
    depends_on:
      - monapp
    volumes:
      - /home/geek/nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - /home/geek/DjangoSite/media:/app/media

  monapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pip install -r /app/requirements.txt && python manage.py makemigrations && python manage.py migrate && gunicorn blog.wsgi:application --bind 0.0.0.0:8080"
    depends_on:
      - db
    expose:
      - 8080
    volumes:
      - static_volume:/app/staticfiles
      - .:/app
    networks:
      - monreseau
    environment:
      - DEBUG=TRUE
      - DB_name=WebSite
      - DB_user=root
      - DB_password=7[)Sb{)!u4]5~H2&1*+|


  db:
    image: mysql
    expose:
      - 3306
    networks:
      - monreseau
    environment:
      - MYSQL_USER=Sylvain
      - MYSQL_ROOT_PASSWORD=7[)Sb{)!u4]5~H2&1*+|
      - MYSQL_DATABASE=WebSite
      - MYSQL_HOST='db'
      - MYSQL_PASSWORD=collectstatic
    volumes:
      - myvolume:/var/lib/mysql

networks:
  monreseau:
volumes:
  static_volume:
  myvolume:
