# Generated by Django 4.0.3 on 2022-03-27 14:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_presentation',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
