# Generated by Django 4.0.3 on 2022-03-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_photo_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_presentation', models.ImageField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_presentation',
        ),
    ]
