# Generated by Django 4.0.3 on 2022-03-27 16:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_photo_remove_article_photo_presentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='article',
            name='photo_presentation',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
