# Generated by Django 4.0.3 on 2022-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_photo_article_photo_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colorBorder',
            field=models.CharField(default='#000000', help_text='code hexa couleur', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(default='31 Mar 2022', max_length=100),
        ),
    ]
