# Generated by Django 4.0.3 on 2022-03-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_colorborder_alter_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='photo_presentation',
            new_name='photoPresentation',
        ),
    ]
